
import NavBar from '@/components/my-comnonents/NavBar'
import Footer from '@/components/my-comnonents/Footer'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className={inter.className} >
     <NavBar/>
    <div>
    {children}
    <div className=' bg-gray-200 px-5 md:px-20'>
    <Footer/>
    </div>
 
    </div>
        </body>
      
    </html>
  )
}
